### ISSUE TITLE
Mark a todo as done

### ISSUE THREAD

**Issue by codeliner** [prooph/proophessor-do#1]
1. Create a dedicated command for the action called `MarkTodoAsDone` and put it into the [todo command folder](https://github.com/prooph/proophessor-do/tree/master/src/Model/Todo)
2. Create a command handler for the new command
    - Create a factory for the command handler and put it [here](https://github.com/prooph/proophessor-do/tree/master/src/Container/Model/Todo)
    - The command handler needs to fetch an existing Todo from the [TodoList](https://github.com/prooph/proophessor-do/blob/master/src/Model/Todo/TodoList.php) so inject the TodoList as dependency into the command handler using the factory
    - Make the command handler available in the container by using the command handler FQCN as service name and point it to the factory. See [configuration](https://github.com/prooph/proophessor-do/blob/master/config/services.php#L55) for the PostTodoCommandHandler as an example
3. Now you can route the command to its handler
    - Route the http request representing the command to the [Commanding\API](https://github.com/prooph/proophessor-do/blob/master/src/App/Commanding/API.php).
You can do this in the [routes configuration](https://github.com/prooph/proophessor-do/blob/master/config/routes.php#L53).
    - The API will translate the request into a command message and dispatch the message on the command bus. The command bus is responsible to locate and invoke the responsible command handler. To do so the command bus also need some [route information](https://github.com/prooph/proophessor-do/blob/master/config/prooph.php#L24). 
4. In the command handler you should load the effected Todo from the TodoList
5. The Todo aggregate root is responsible for handling the action so it needs a new method to do so.
    - In the method the Todo should check it's current status. Only if it is **open** it can be marked as done otherwise it should throw an exception
    - If the precondition is met the Todo should not change it's state directly but instead record a new domain event called `TodoWasMarkedAsDone`
    - Add a state changing method in the Todo aggregate root based on the new event. Call the method `whenTodoWasMarkedAsDone` and require the recorded event as a input parameter then change the `TodoStatus` to `done`
6. The same event needs also be handled by a projector so that the read model gets updated. You already know how to route a command message to a handler. Now do the same for the event and route it to a projector which updates the read model table.

*Bonus Points: Write at least one unit test which covers that an open Todo can change its state to done and records a  `TodoWasMarkedAsDone` event to track the change.*

**Comment by codeliner** [comment]
@DannyvdSluijs please submit your PR against the `develop` branch of proophessor-do. Thanks

**Comment by DannyvdSluijs** [comment]
@codeliner Yes will do.
