### ISSUE TITLE
Simplify Installation.md

### ISSUE THREAD

**Issue by mablae** [prooph/proophessor-do#100]
Hello, 

My overall approach is to keep things as simple as possible and don't force the user 
to "decide" on all options, when installing the app for first time. 

There are two things: 
 - Remove snapshot-store introductions => Refer to the snapshotting tutorial in end of Installation.md
 - Decide for one RDMS: MySql OR Postgres ? 

What do you think? Also see #98 where I already started with this.

**Comment by prolic** [comment]
- Remove snapshot store introduction
:-1: We can add a complete new paragraph for this, like advanced configuration (not required)

- Decide for one RDMS: MySql OR Postgres
Definitely MySQL, this is the stuff that everyone has already installed. But we can add postgres note and how to setup it in the advanced configuration section.

**Comment by mablae** [comment]
Basically done and merged into prooph_v7. 

Closing.
