### ISSUE TITLE
docs are missing snapshot details

### ISSUE THREAD

**Issue by basz** [prooph/proophessor-do#109]
https://github.com/prooph/proophessor-do/blob/develop/docs/installation/manual.md

**Comment by prolic** [comment]
@basz we have here https://github.com/prooph/proophessor-do/blob/develop/docs/installation/manual.md - 4.2 Start snapshotters (only if you decided to use 3.4)

what is missing exactly?

**Comment by prolic** [comment]
superseeded with https://github.com/prooph/proophessor-do/issues/124
