### ISSUE TITLE
HTTP 500 Error on creating new user

### ISSUE THREAD

**Issue by BartoszBartniczak** [prooph/proophessor-do#120]
When I am trying to create new user, the API response for request http://localhost:8080/api/commands/register-user is HTTP 500.

I'm using docker version, which was installed step by step with instruction. The only thing which reported problem was the `setup_mongodb.sh` script, which returned error:

```bash
Starting proophessordo_dataphp_1
bin/setup_mongodb.sh: 3: bin/setup_mongodb.sh: Bad substitution
using adapter mongodb
``` 

Both files were created (`config/autoload/mongo_client.local.php` and `config/autoload/event_store.local.php`), so i assume it works properly.

The JSON response for the request looks like:

```json
{"message":"Server Error"}
```
so it is not helpful. Is there any way to turn on the debug mode? Did I do something wrong?

**Comment by prolic** [comment]
Are the projections running?

Am 09.03.2017 22:24 schrieb "Bartosz Bartniczak" <notifications@github.com>:

**Comment by BartoszBartniczak** [comment]
@prolic I'm sorry, I don't understand. What do you mean by "projections"? Docker containers?

**Comment by prolic** [comment]
Are you referring master or develop branch?

**Comment by BartoszBartniczak** [comment]
@prolic Master. I just cloned the repo.

**Comment by codeliner** [comment]
Debug mode can be enabled, see the note at the end: https://github.com/prooph/proophessor-do/blob/master/docs/installation.md#step-4---view-it

**Comment by BartoszBartniczak** [comment]
@codeliner 
Thanks, this worked. Now I can see the problem more detailed ;)

@prolic 
![image](https://cloud.githubusercontent.com/assets/6022713/23830319/61cafa54-0708-11e7-8d18-a9a1580f9eb9.png)
There is a problem with example app. I haven't changed nothing in code.

**Comment by BartoszBartniczak** [comment]
I have found the problem.

```
Message dispatch failed during locate-handler phase. Error: Service with name "doctrine.connection.default" could not be created. Reason: No options set for configuration "doctrine"
```

![image](https://cloud.githubusercontent.com/assets/6022713/23830655/33eedbf2-0710-11e7-89a4-21b732b909c6.png)

I will be looking for solution :-)

**Comment by sandrokeil** [comment]
@BartoszBartniczak Looks like you don't follow the install instructions and activated the doctrine connection. Please refer to the install instructions in the docs folder.

**Comment by prolic** [comment]
agree with @sandrokeil  - cannot reproduce.

**Comment by BartoszBartniczak** [comment]
@sandrokeil @prolic I just did the first, four steps for basic installation, nothing else.

On MariaDB driver I can create users, tasks, deadlines but I can't add reminders, see:

![image](https://cloud.githubusercontent.com/assets/6022713/23921571/66243932-08ff-11e7-88de-66c1bed46ce2.png)

This is the same error, as above.

**Comment by codeliner** [comment]
ok, if the other operations work we may have a real error now. You use docker, so you can look at the logs with `docker-compose logs php`

The original exception is wrapped with a `CommandDispatchException`, see here: https://github.com/prooph/service-bus/blob/v5.2.0/src/CommandBus.php#L79

So in the logs you can find the error causing dispatch to fail.

**Comment by BartoszBartniczak** [comment]
I think this is the previous exception:

```
Message dispatch failed during invoke-handler phase. Error: Prooph\ProophessorDo\Model\Todo\TodoReminderStatus::open not defined
```

![image](https://cloud.githubusercontent.com/assets/6022713/23956365/c2ed2df2-099c-11e7-8987-3b1bdbc0eb9a.png)

**Comment by codeliner** [comment]
Looks like a spelling issue... should be `TodoReminderStatus::OPEN` not `TodoReminderStatus::open` I guess, but I need the line of code that causes the error.

**Comment by BartoszBartniczak** [comment]
I think this same, but I can't locate it. It's weird, because everything in the code seems to be ok.

**Comment by codeliner** [comment]
but the stack trace should tell you the root of the error. What line of code causes the error

**Comment by BartoszBartniczak** [comment]
I think I found the problem.

`TodoReminder::from` uses `fromName()` method:

![image](https://cloud.githubusercontent.com/assets/6022713/23958636/097730f0-09a3-11e7-8fb3-c4ce1015a734.png)

but `TodoReminderStatus` constants are not same as values:

![image](https://cloud.githubusercontent.com/assets/6022713/23958679/2c570406-09a3-11e7-85cb-bca4b1df3fa1.png)

**Comment by codeliner** [comment]
damn, good catch. Can you provide a bugfix and a unit test? Looks like we missed that.

**Comment by BartoszBartniczak** [comment]
In fact unit tests don't work either :P
![image](https://cloud.githubusercontent.com/assets/6022713/23960340/0295ae24-09a8-11e7-9a2a-cd467626c1eb.png)

**Comment by BartoszBartniczak** [comment]
There is a lot of inconsistency in the code, sometimes name is used, sometimes value. In fact this data structure (Enum) is a little bit unfortunate.

**Comment by codeliner** [comment]
ok, strange. Not sure what is going on. Tests should have passed in the past. I cannot imagine that we've merged a change without running the tests. Can look at it the next days.

**Comment by BartoszBartniczak** [comment]
I did PullRequest so you can merge changes. It fixes all the problems (using Docker PHP interpreter), but look at the build https://travis-ci.org/prooph/proophessor-do/builds/211433771

**Comment by codeliner** [comment]
last master build was ok, except doc header checks: https://travis-ci.org/prooph/proophessor-do/builds/196271988
