### ISSUE TITLE
Fatal error in history_replay script (replay function undefined)

### ISSUE THREAD

**Issue by foxriver85** [prooph/proophessor-do#141]
Hello,
I have a problem with replaying history when i run the history_replay script.
I have a fatal error which tells that the function replay is undefined.

> Call to undefined method Prooph\EventStore\ActionEventEmitterEventStore::replay() in /app/scripts/history_replay.php

Do you have an idea about that?
Thanks.

**Comment by prolic** [comment]
The EventStore has no replay method, that's correct.
I just created a PR (https://github.com/prooph/proophessor-do/pull/142) to remove this script.
For current proophessor-do implementation, you need to restart the projection.

**Comment by foxriver85** [comment]
Thank you for your reply.

**Comment by prolic** [comment]
Any time
