### ISSUE TITLE
Installation is broken

### ISSUE THREAD

**Issue by bgaleotti** [prooph/proophessor-do#148]
After #143 `http-interop/http-middleware` was upgraded to `0.5.0` which is not yet supported by `zendframework/zend-expressive` (https://github.com/zendframework/zend-expressive/issues/513).

**Comment by basz** [comment]
I see the reason now - you are correct. But instead of downgrading the requirement, could you change the PR to require either "*" or "^0.2 | ^0.3 | ^0.4 | ^0.5" since #143 ensures we can work with any of them.
