### ISSUE TITLE
Call to private property

### ISSUE THREAD

**Issue by darrylhein** [prooph/proophessor-do#168]
I could be missing something, but [in this line](https://github.com/prooph/proophessor-do/blob/b92605ab1406d26139f6d1e55842bdf0d49c9491/src/Model/Todo/Todo.php#L291) will it not fail because `$todoId` is a private property?

    $this->todoId->sameValueAs($other->todoId);

Should it be?

    $this->todoId->sameValueAs($other->todoId());

I can submit a pull request.

**Comment by prolic** [comment]
Private scope is class scope, not object scope. So this works. Try it.
