### ISSUE TITLE
Question: AggregateChanged payload only vs properties

### ISSUE THREAD

**Issue by lfridael** [prooph/proophessor-do#169]
This is one of the better event sourcing examples I've come across. Kudos!

One question: why do the `AggregateChanged` events store their properties in both the payload and in instance properties?

From: https://github.com/prooph/proophessor-do/blob/master/src/Model/Todo/Event/TodoWasPosted.php

```php
    public function assigneeId(): UserId
    {
        if (null === $this->assigneeId) {
            $this->assigneeId = UserId::fromString($this->payload['assignee_id']);
        }
        return $this->assigneeId;
    }
```

could be simplified to:

```php
    public function assigneeId(): UserId
    {
        return UserId::fromString($this->payload['assignee_id']);
    }
```

There might be a slight performance penalty here, but that would, in practice, depend on how many times this getter is invoked.

I'm trying to reduce boilerplate in my app, hence the question.

**Comment by prolic** [comment]
Yes you can do this. To avoid writing boilerplate use prolic/fpp

**Comment by lfridael** [comment]
Thanks for the confirmation. 👍 Closing this issue.
