### ISSUE TITLE
docker issues.

### ISSUE THREAD

**Issue by TerraSkye** [prooph/proophessor-do#176]
unable to startup docker

ERROR: Get https://registry-1.docker.io/v2/library/mongo/manifests/sha256:d2a3543d1bcfb6208cde0c1e89df39b51731a249d42fb4c1552f72f817e8507d: dial tcp: lookup registry-1.docker.io on 127.0.0.1:53: read udp 127.0.0.1:40902->127.0.0.1:53: read: connection refused

**Comment by prolic** [comment]
Try again? Maybe just internet connection issues. Never had this problem before.

**Comment by TerraSkye** [comment]
ive resolved the issue trough https://github.com/docker/for-mac/issues/1317 im not behind a proxy but setting chaning the dns of docker fixed my issues.

**Comment by prolic** [comment]
Glad you solved it
