### ISSUE TITLE
xhr,  thrown exception ,(/event-store/streams)

### ISSUE THREAD

**Issue by m9rco** [prooph/proophessor-do#177]
error message:

```php
Fatal error: Uncaught Zend\View\Exception\RuntimeException: Zend\View\Renderer\PhpRenderer::render: Unable to render template "layout::default"; resolver could not resolve to a file in /var/www/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php:498 Stack trace: #0 /var/www/vendor/zendframework/zend-expressive-zendviewrenderer/src/ZendViewRenderer.php(220): Zend\View\Renderer\PhpRenderer->render(NULL) #1 /var/www/vendor/zendframework/zend-expressive-zendviewrenderer/src/ZendViewRenderer.php(140): Zend\Expressive\ZendView\ZendViewRenderer->renderModel(Object(Zend\View\Model\ViewModel), Object(Zend\View\Renderer\PhpRenderer)) #2 /var/www/vendor/zendframework/zend-expressive/src/Response/ErrorResponseGeneratorTrait.php(70): Zend\Expressive\ZendView\ZendViewRenderer->render('error::error', Array) #3 /var/www/vendor/zendframework/zend-expressive/src/Middleware/ErrorResponseGenerator.php(58): Zend\Expressive\Middleware\ErrorResponseGenerator->prepareTemplatedResponse(Object(Zend\ServiceManager\Exception\ServiceNotFoundE in /var/www/vendor/zendframework/zend-view/src/Renderer/PhpRenderer.php on line 498
```

**Comment by m9rco** [comment]
![image](https://user-images.githubusercontent.com/18391791/63226300-cf9ac900-c20a-11e9-9e22-41c03ad4268d.png)

**Comment by codeliner** [comment]
I've tested a fresh installation of proophessor-do using the docker set up. Mgmt UI works for me:

![image](https://user-images.githubusercontent.com/5131987/63508049-73b99400-c4d9-11e9-9264-c0c6a984e946.png)

Did you run all installation steps? Can you add a user and todos in the example app?
What set up are you using?

**Comment by m9rco** [comment]
Cloning the latest code, I use the docker-compose the installation，Can you try to delete the local image, and then install，

**Comment by codeliner** [comment]
I've removed source code completely. Cloned a fresh copy from Github and pulled latest docker containers. Then I followed this installation guide: https://github.com/prooph/proophessor-do/blob/master/docs/installation/docker.md

Are you able to add a user in the example application?

**Comment by m9rco** [comment]
cannot,  It will be another mistake, According to you for your prompt, I use https://event-engine.io,Thank you, it can be run

**Comment by codeliner** [comment]
Using Event Engine is the recommended way. Good choice :+1:
