### ISSUE TITLE
bin-dir entry in composer.json is invalid

### ISSUE THREAD

**Issue by sandrokeil** [prooph/proophessor-do#30]
The bin-dir entry must be set under the [config key](https://getcomposer.org/doc/articles/vendor-binaries.md#can-vendor-binaries-be-installed-somewhere-other-than-vendor-bin-). Vendor binaries are not available in bin folder.

**Comment by codeliner** [comment]
PR :smile: ?

**Comment by sandrokeil** [comment]
Alright. This evening. I thought maybe you don't need it anymore.

**Comment by codeliner** [comment]
mhmm, we have our own migrations.php script in the bin folder. That is the only script a user needs to process in order to get the application running. Removing the config is better. Thanks.

**Comment by codeliner** [comment]
Done with #31
