### ISSUE TITLE
Support for Docker and Vagrant

### ISSUE THREAD

**Issue by sandrokeil** [prooph/proophessor-do#34]
To further simplify the installation steps, I can write Docker files which does the job. Vagrant can be used with these Dockerfiles too. 

What do you think and which server stack should it be?

**Comment by codeliner** [comment]
nice, would be a great addition and allow us to easily switch between different set ups like running the app with mongo db adapter or Doctrine DBAL adapter :+1: .

As soon as one of the "todo deadline" tasks is in progress (ping @theDisco ;)) we will also integrate the async message producers available for prooph/service-bus so we will need to install for example zeromq, amqp, a redis backend and so on.

server stack? Well, choose the one you prefer most. Installing PHP extensions and up-to-date versions of the listed systems above should be possible.

**Comment by sandrokeil** [comment]
I've started the work in branch [vagrant-docker](https://github.com/sandrokeil/proophessor-do/tree/docker-vagrant).

**Comment by codeliner** [comment]
@sandrokeil :+1: looking forward to the docker integration. FYI I've created a prooph account at docker hub.

**Comment by sandrokeil** [comment]
Already merged
