### ISSUE TITLE
Add deadline to todo

### ISSUE THREAD

**Issue by theDisco** [prooph/proophessor-do#35]
* User should be able to add a deadline as a date in the future to a todo
* User should not be able to add a deadline, if the date is in the past

**Comment by codeliner** [comment]
:+1: 

One addition: User must be the owner of the todo

FYI: I'm currently planing oauth2 integration and also moving user handling into its own context. This change should not effect your task that much.

When we have the deadline feature in place we can think about how to monitor the deadlines.

**Comment by theDisco** [comment]
Merged into master.

**Comment by codeliner** [comment]
@theDisco small correction: PR is merged into **develop**. As soon as #40 and #39 are also merged into develop, we will merge all changes into *master* and release a new version.

**Comment by theDisco** [comment]
Old habits :D
