### ISSUE TITLE
POST methods are returning content.

### ISSUE THREAD

**Issue by bweston92** [prooph/proophessor-do#6]
When creating a task if validation fails there should be a redirect to "create a todo" view with a validation error message. Having the view returned in that POST request allows the user to press F5 and re-attempt the previous request which may confuse them when "are you sure you want to send that data again" pops up.

This is known as Post/Validate/Redirect or Post/Redirect/Get pattern. POST is your action and GET is your query.

**Comment by codeliner** [comment]
@bweston92 good catch! Please have a look at the current develop branch of proophessor-do. Your issue is solved there as we no longer handle forms server side but directly send commands to the backend using JavaScript.
