### ISSUE TITLE
Add reminder to todo

### ISSUE THREAD

**Issue by codeliner** [prooph/proophessor-do#60]
- User should be the owner of the todo
- User should be able to add a reminder as a date in the future to a todo
- User should not be able to add a reminder, if the date is in the past

**Comment by codeliner** [comment]
Depends on #1 

Step By Step Guide

1. Create a dedicated command for the action called `AddReminderToTodo` and put it into the [todo command folder](https://github.com/prooph/proophessor-do/tree/master/src/Model/Todo)
2. Create a command handler for the new command
    - Create a factory for the command handler and put it [here](https://github.com/prooph/proophessor-do/tree/master/src/Container/Model/Todo)
    - The command handler needs to fetch an existing Todo from the [TodoList](https://github.com/prooph/proophessor-do/blob/master/src/Model/Todo/TodoList.php) so inject the TodoList as dependency into the command handler using the factory
    - Make the command handler available in the container by using the command handler FQCN as service name and point it to the factory. See [configuration](https://github.com/prooph/proophessor-do/blob/master/config/services.php#L55) for the PostTodoCommandHandler as an example
3. Now you can route the command to its handler
    - Route the http request representing the command to the command handling middleware.
You can do this in the [routes configuration](https://github.com/prooph/proophessor-do/blob/master/config/routes.php#L53).
    - The middleware will translate the request into a command message and dispatch the message on the command bus. The command bus is responsible to locate and invoke the responsible command handler. To do so the command bus also need some [route information](https://github.com/prooph/proophessor-do/blob/master/config/prooph.php#L24). 
4. In the command handler you should load the effected Todo from the TodoList
5. Implement a `AddReminderToTodo::reminder` method that returns a `TodoReminder` value object. See `TodoDeadline` and `AddDeadlineToTodo` as an example.
6. The Todo aggregate root is responsible for handling the action so it needs a new method.
    - In the method the Todo should check it's current status. Only if it is **open** a reminder can be added otherwise it should throw an exception
    - If the preconditions are met the Todo should not change its state directly but instead record a new domain event called `ReminderWasAddedToTodo`
    - Add a state changing method in the Todo aggregate root based on the new event. Call the method `whenReminderWasAddedToTodo` and require the recorded event as input parameter. Pull the `TodoReminder` value object from the event and add it to the Todo.
7. The same event needs also be handled by a projector so that the read model gets updated. You already know how to route a command message to a handler. Now do the same for the event and route it to a projector which updates the read model table `read_todo`. The read table needs to be aligned. Add a new migration class and in the migration add a new column called "reminder" to the table.

*Bonus Points: Write at least one unit test which covers that a reminder can be added to a Todo.*

**Comment by rommsen** [comment]
I will try to do this

**Comment by prolic** [comment]
:+1:
