### ISSUE TITLE
Aura router produces php notice

### ISSUE THREAD

**Issue by codeliner** [prooph/proophessor-do#64]
the route:

``` php
[
            'name' => 'page::user-todo-list',
            'path' => '/user-todo-list/{user_id}',
            'middleware' => \Prooph\ProophessorDo\App\Action\UserTodoList::class,
            'allowed_methods' => ['GET'],
            'options' => [
                'tokens' => [
                    'user_id' => '[0-9A-Fa-f]{8}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{4}-[0-9A-Fa-f]{12}'
                ],
            ],
        ],
```

produces a PHP Notice:

``` bash
PHP Notice:  Array to string conversion in /var/www/proophessor-do/vendor/aura/router/src/Generator.php on line 131
```

This can cause trouble as routes are assembled and injected into JS code so the notice breaks JS syntax then.

We should check if we can avoid the notice and also improve the JS parser (or replace it with a better mechanism).

**Comment by prolic** [comment]
when using multiple middlewares like:

    'middleware' => [
        \Prooph\ProophessorDo\Middleware\JsonPayload::class,
        \Prooph\Psr7Middleware\CommandMiddleware::class,
    ],

the router get an array of {action} params and will create this notice.

**Comment by prolic** [comment]
Seems to be a bug in either zend-expressive or zend-expressive-aurarouter, could not yet find out
