### ISSUE TITLE
Mark todo as expired feature

### ISSUE THREAD

**Issue by dranzd** [prooph/proophessor-do#75]
What's the requirement for this feature?  

Is this a feature where user sends a command to mark as expired or is this marked by the system when it goes expired?

Does expired means that the current time is past that deadline?

**Comment by codeliner** [comment]
Hey @dranzd , do you want to take over the task? Yes, the system should mark a todo as expired when time has passed the deadline set by the user.

Similar to #73 a script is needed with a worker checking all open todos with a deadline and if one deadline has gone past a MarkTodoAsExpired command should be dispatched by the worker.
Let me know if you need more information.

**Comment by dranzd** [comment]
@codeliner yes I want to try it out.  I've already started that and most of the questions above are just to confirm that I understand what the feature does.

**Comment by codeliner** [comment]
cool, looking forward to your PR

**Comment by codeliner** [comment]
PR merged #76 . Works like a charm.
