### ISSUE TITLE
Notify assignee when todo deadline is expired feature

### ISSUE THREAD

**Issue by mikemix** [prooph/proophessor-do#82]
@prolic / @codeliner What's the requirement for this feature?

Am I supposed to subscribe to the event when the todo is marked as expired and notify the assignee about the fact?

**Comment by prolic** [comment]
@mikemix Exactly. Additionally you need to trigger this event, measure timeout with amqp or a cronjob

**Comment by mikemix** [comment]
What event am I supposed to trigger? Though just adding a subscriber when the MarkTodoAsExpired command is dispatched would be enough.

**Comment by prolic** [comment]
The MarkTodoAsExpired command is not dispatched! Therefore we need a cronjob or amqp to check expired todos and send the command.

**Comment by prolic** [comment]
Ah sorry, the script for detecting expired todos is already there (https://github.com/prooph/proophessor-do/blob/master/scripts/mark_expired_todos.php). Sorry!

So you only need to attach a listener to TodoWasMarkedAsExpired and send an email to the user.

**Comment by codeliner** [comment]
Add with #84
