### ISSUE TITLE
Final classes

### ISSUE THREAD

**Issue by mikemix** [prooph/proophessor-do#83]
Why the read model repositories are marked as final?

* It's impossible to unit test classes depending upon them, or at least it is possible with lots of mocking of the Doctrine's Connection/Statement class
* [Quoting Marco Pivetta](https://ocramius.github.io/blog/when-to-declare-classes-final/):

> Final classes only work effectively under following assumptions: There is an abstraction (interface) that the final class implements, All of the public API of the final class is part of that interface

An interface should be introduced or the `final` removed then.

**Comment by prolic** [comment]
I'm for remove final keyword. Having a finder interface makes no sense, especially when QueryBus (https://github.com/prooph/proophessor-do/issues/22) is used in this app.

your thought @codeliner ?

**Comment by sandrokeil** [comment]
@mikemix Good catch. We should remove the final keyword.

**Comment by codeliner** [comment]
yeah, we can remove the final keyword in this case. "final" is part of my template for new classes and I've forgotten to remove it for the finders. Good catch @mikemix
