### ISSUE TITLE
Use Docker Compose V2 config and PHP 7

### ISSUE THREAD

**Issue by sandrokeil** [prooph/proophessor-do#85]
We can update the Docker Compose configuration to the new version and we can use PHP 7, because the [MongoDB adapter](https://github.com/prooph/event-store-mongodb-adapter/releases/tag/v2.3.0) supports PHP 7.
- [ ]  :whale: User Docker Compose V2 config
- [ ] Remove Docker data container and mount files in PHP image (not needed here and has no benefit)
- [ ] :rocket: Use PHP 7 only
- [ ] :memo: Update install instructions

**Comment by mikemix** [comment]
What happens if there's any change in the php image? Won't data I have worked on get lost?

**Comment by sandrokeil** [comment]
The PHP data will not be lost. We simply mount a host directory in the PHP container. You can switch between Docker images without loosing your data.

**Comment by codeliner** [comment]
the setup scripts need to be aligned, too. `line 3: syntax error: bad substitution` using php:7.1-fpm-alpine

**Comment by sandrokeil** [comment]
Closing this in favor of #98
