### ISSUE TITLE
Retrying failing events?

### ISSUE THREAD

**Issue by mrook** [prooph/proophessor-do#87]
I'm slightly intrigued by the following line:

https://github.com/prooph/proophessor-do/blob/master/scripts/history_replay.php#L88

Why do you choose to retry events that can't be replayed? This could lead to inconsistent read models when subsequent events on the same aggregate are successfully replayed.

**Comment by prolic** [comment]
how you replay history is always very specific to your project's needs. in this case, a behaviour like this is absolutely correct. in other domains, that may not be to possible. this history replay script is not breaking the rules for this domain, not should you simply copy & paste to use it. it's purpose is to demonstrate how you _could_ replay events.

For more discussion, visit our chat at: https://gitter.im/prooph/improoph
