### ISSUE TITLE
Composer could not find a composer.json file in /app

### ISSUE THREAD

**Issue by astavale** [prooph/proophessor-do#88]
Followed the docker instructions in the docs/installation.md on Fedora 23.

The first step worked fine. This was:
docker pull prooph/php:5.6-fpm && docker pull prooph/composer:5.6 && docker pull prooph/nginx:www
but the next step is reporting "Composer could not find a composer.json file in /app". This is after the command:
docker run --rm -it --volume $(pwd):/app prooph/composer:5.6 install -o --prefer-dist
Plus the warning "Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted".

**Comment by astavale** [comment]
Working now, but there are two things that could be added to the installation instructions:

1. If you are using a distribution with SELinux then the right security context needs to be set. After git cloning the `prooph/proophessor-do` repo issue the command:
`chcon -Rt svirt_sandbox_file_t proophessor-do/`

1. All Docker commands should be run from within the `proophessor-do` directory. So first of all:
`cd proophessor-do`

**Comment by sandrokeil** [comment]
@astavale Thanks for your issue. Can you bring a PR please?
