### ISSUE TITLE
Don't return error when email address is already used

### ISSUE THREAD

**Issue by prolic** [prooph/proophessor-do#95]
Just accept the command and send email appropriately.
a) If email is new, send welcome registration email.
b) If email is used already, inform user of duplicate registration via email.

This is for preventing to find out registered users by trying different email addresses.

See also: https://github.com/prooph/proophessor-do/pull/93 & https://github.com/prooph/proophessor-do/pull/94

**Comment by lucascourot** [comment]
👍
