### ISSUE TITLE
'Manage Todos' menu item seems broken

### ISSUE THREAD

**Issue by mablae** [prooph/proophessor-do#99]
![image](https://cloud.githubusercontent.com/assets/389360/21079722/03afaa3c-bf9b-11e6-80f5-47534d5fde92.png)

In prooph v7 this item does not do anything. Didn't test master though

**Comment by codeliner** [comment]
same on master ;) No features defined for the menu item, yet

**Comment by codeliner** [comment]
Can be closed. Solved in the light theme #101
